/* SPDX-License-Identifier: CC0-1.0
 *
 * The 32-bit core is built for SSE2, which an Athlon XP or a Pentium III does
 * not have. 947 instructions are outside SSE1; every one has an SSE1 form that
 * computes the same bits.
 *
 *   movq m64,xmm    -> movlps m64,xmm        exactly the same 64 bits stored
 *   movq xmm,m64    -> movlps xmm,m64        where the upper lane is dead
 *   pxor xmm,xmm    -> xorps xmm,xmm
 *   movd xmm,m32    -> movss xmm,m32         both zero what is above
 *   movq/movsd load -> xorps + movlps        where the upper lane is live
 *   sqrtsd          -> the x87 does the root
 *
 * The rewrites that stay in place are one byte shorter than what they replace
 * and the spare byte becomes a leading nop, never a trailing one: modrm and
 * any displacement have to keep the offsets the relocation table records for
 * them. Getting that wrong is invisible until a second engine is mapped away
 * from its preferred base and every absolute operand in it is rewritten.
 *
 * Sites come from src/sse2_sites.h, generated by disassembling one known core,
 * so the opcode bytes are checked before anything is touched and a core that
 * disagrees is left alone. The patch must run after relocations, because the
 * stubs copy operand bytes that relocation has already corrected.
 */
#ifndef SCVA_SSE2_SHIM_H
#define SCVA_SSE2_SHIM_H
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include "sse2_sites.h"
#include "sse2_cvt.h"

/* a zero-extending load stub is xorps + movlps + ret, and the longest
   operand encoding here is seven bytes */
#define SCVA_SSE2_ARENA (SCVA_SSE2_SITES * 24)

/* EDX bit 26 of cpuid leaf 1. */
static int scva_cpu_has_sse2(void)
{
#if defined(__i386__) || defined(__x86_64__)
  unsigned int a = 1, b = 0, c = 0, d = 0;
#if defined(__i386__) && defined(__PIC__)
  __asm__ volatile("xchgl %%ebx, %1\n\tcpuid\n\txchgl %%ebx, %1"
                   : "+a"(a), "=r"(b), "=c"(c), "=d"(d));
#else
  __asm__ volatile("cpuid" : "+a"(a), "=b"(b), "=c"(c), "=d"(d));
#endif
  (void)a; (void)b; (void)c;
  return (d & (1u << 26)) != 0;
#else
  return 1;
#endif
}

/* the three opcode bytes each kind must start with, so a core that is not the
   one the table was generated from is recognised rather than corrupted */
static int scva_sse2_expected(int kind, const unsigned char *p)
{
  switch (kind) {
    case 1: return p[0] == 0x66 && p[1] == 0x0f && p[2] == 0xd6;   /* movq m,x */
    case 2: return p[0] == 0xf3 && p[1] == 0x0f && p[2] == 0x7e;   /* movq x,m */
    case 3: return p[0] == 0x66 && p[1] == 0x0f && p[2] == 0xef;   /* pxor    */
    case 4: return p[0] == 0x66 && p[1] == 0x0f && p[2] == 0x6e;   /* movd    */
    case 5: return (p[0] == 0xf3 && p[1] == 0x0f && p[2] == 0x7e)  /* movq    */
                || (p[0] == 0xf2 && p[1] == 0x0f && p[2] == 0x10); /* movsd   */
    case 6: return p[0] == 0xf2 && p[1] == 0x0f && p[2] == 0x51;   /* sqrtsd  */
    case 7: return 1;                          /* checked against sse2_cvt.h */
    default: return 0;
  }
}


/* [esp] is mod 00, rm 100 with a SIB of 0x24 */
static size_t scva_x87_cvt(unsigned char *o, int form, int dreg, int sreg)
{
  size_t n = 0;
  /* lea, not sub: the flags here are live across the span in at least one
     loop, whose jne tests a counter decremented before it */
  o[n++] = 0x8d; o[n++] = 0x64; o[n++] = 0x24; o[n++] = 0xf8; /* lea esp,-8  */
  if (form == 3) {
    /* a whole integer to a single is cvtsi2ss, which SSE1 already has, so
       this one never touches the x87 */
    o[n++] = 0xf3; o[n++] = 0x0f; o[n++] = 0x11;             /* movss [esp], */
    o[n++] = (unsigned char)(0x04 | (sreg << 3)); o[n++] = 0x24;
    o[n++] = 0xf3; o[n++] = 0x0f; o[n++] = 0x2a;             /* cvtsi2ss     */
    o[n++] = (unsigned char)(0x04 | (dreg << 3)); o[n++] = 0x24;
    o[n++] = 0x8d; o[n++] = 0x64; o[n++] = 0x24; o[n++] = 0x08; /* lea esp,+8 */
    return n;
  }
  if (form == 1) {                                           /* 32-bit in    */
    o[n++] = 0xf3; o[n++] = 0x0f; o[n++] = 0x11;             /* movss [esp], */
    o[n++] = (unsigned char)(0x04 | (sreg << 3)); o[n++] = 0x24;
  } else {                                                   /* 64-bit in    */
    o[n++] = 0x0f; o[n++] = 0x13;                            /* movlps [esp],*/
    o[n++] = (unsigned char)(0x04 | (sreg << 3)); o[n++] = 0x24;
  }
  if (form == 1)      { o[n++] = 0xd9; }                     /* fld  dword   */
  else if (form == 3) { o[n++] = 0xdb; }                     /* fild dword   */
  else                { o[n++] = 0xdd; }                     /* fld  qword   */
  o[n++] = 0x04; o[n++] = 0x24;
  if (form == 1) { o[n++] = 0xdd; }                          /* fstp qword   */
  else           { o[n++] = 0xd9; }                          /* fstp dword   */
  o[n++] = 0x1c; o[n++] = 0x24;
  if (form == 1) {                                           /* 64-bit out   */
    o[n++] = 0x0f; o[n++] = 0x12;                            /* movlps xmm,  */
    o[n++] = (unsigned char)(0x04 | (dreg << 3)); o[n++] = 0x24;
  } else {                                                   /* 32-bit out   */
    o[n++] = 0xf3; o[n++] = 0x0f; o[n++] = 0x10;             /* movss xmm,   */
    o[n++] = (unsigned char)(0x04 | (dreg << 3)); o[n++] = 0x24;
  }
  o[n++] = 0x8d; o[n++] = 0x64; o[n++] = 0x24; o[n++] = 0x08; /* lea esp,+8  */
  return n;
}

/* A jump rather than a call, so esp is what the replayed neighbour expects.
   Returns how many conversions were rewritten. */
static int scva_sse2_patch_cvt(unsigned char *base, unsigned char *arena,
                               size_t arena_len, size_t *used_io)
{
  static const unsigned char head[5][4] = {
    {0,0,0,0},
    {2, 0x0f, 0x5a, 0},          /* cvtps2pd */
    {3, 0xf2, 0x0f, 0x5a},       /* cvtsd2ss */
    {2, 0x0f, 0x5b, 0},          /* cvtdq2ps */
    {3, 0x66, 0x0f, 0x5a}        /* cvtpd2ps */
  };
  size_t used = *used_io;
  int i, hits = 0;

  for (i = 0; i < SCVA_SSE2_CVTS; ++i) {
    const unsigned char *h = head[scva_sse2_cvt[i].form];
    unsigned char *p = base + scva_sse2_cvt[i].rva;
    int at = scva_sse2_cvt[i].at, len = scva_sse2_cvt[i].len;
    int k;
    for (k = 0; k < h[0]; ++k)
      if (p[at + k] != h[1 + k]) return -1;
    (void)len;
  }

  for (i = 0; i < SCVA_SSE2_CVTS; ++i) {
    unsigned char *p = base + scva_sse2_cvt[i].rva;
    unsigned char *stub = arena + used;
    int at = scva_sse2_cvt[i].at, len = scva_sse2_cvt[i].len;
    int span = scva_sse2_cvt[i].span;
    int tail = span - at - len;
    size_t n = 0;
    long long rel;

    if (used + 64 > arena_len) break;
    if (at) { memcpy(stub, p, (size_t)at); n += (size_t)at; }   /* before */
    n += scva_x87_cvt(stub + n, scva_sse2_cvt[i].form,
                      scva_sse2_cvt[i].dreg, scva_sse2_cvt[i].sreg);
    if (tail > 0) { memcpy(stub + n, p + at + len, (size_t)tail); n += (size_t)tail; }
    rel = (long long)((p + span) - (stub + n + 5));             /* jump back */
    if (rel < -2147483647LL || rel > 2147483647LL) continue;
    stub[n++] = 0xe9;
    stub[n++] = (unsigned char)(rel & 0xff);
    stub[n++] = (unsigned char)((rel >> 8) & 0xff);
    stub[n++] = (unsigned char)((rel >> 16) & 0xff);
    stub[n++] = (unsigned char)((rel >> 24) & 0xff);

    rel = (long long)(stub - (p + 5));
    if (rel < -2147483647LL || rel > 2147483647LL) continue;
    p[0] = 0xe9;
    p[1] = (unsigned char)(rel & 0xff);
    p[2] = (unsigned char)((rel >> 8) & 0xff);
    p[3] = (unsigned char)((rel >> 16) & 0xff);
    p[4] = (unsigned char)((rel >> 24) & 0xff);
    memset(p + 5, 0x90, (size_t)span - 5);
    used += n;
    ++hits;
  }
  *used_io = used;
  return hits;
}

/* Returns the number of sites patched, or -1 if the image is not the core the
   table describes. `left` receives how many remain outside SSE1. */
static int scva_sse2_patch(unsigned char *base, unsigned char *arena,
                           size_t arena_len, int *left)
{
  size_t used = 0;
  int i, hits = 0, remaining = 0;

  if (!base || !arena) return -1;

  /* nothing is written until every site has been recognised */
  for (i = 0; i < SCVA_SSE2_SITES; ++i)
    if (!scva_sse2_expected(scva_sse2_site[i].kind,
                            base + scva_sse2_site[i].rva))
      return -1;

  for (i = 0; i < SCVA_SSE2_SITES; ++i) {
    unsigned char *p = base + scva_sse2_site[i].rva;
    int len = scva_sse2_site[i].len;
    int kind = scva_sse2_site[i].kind;
    int oplen = len - 3;                 /* modrm, sib and displacement */

    switch (kind) {
      case 1:                            /* movlps m64,xmm */
      case 2:                            /* movlps xmm,m64 */
      case 3: {                          /* xorps xmm,xmm  */
        unsigned char op1 = kind == 1 ? 0x13 : kind == 2 ? 0x12 : 0x57;
        p[0] = 0x90; p[1] = 0x0f; p[2] = op1;   /* operand bytes stay put */
        ++hits;
        break;
      }
      case 4:                            /* movss xmm,m32, same length */
        p[0] = 0xf3; p[1] = 0x0f; p[2] = 0x10;
        ++hits;
        break;
      case 5: {                          /* xorps xmm,xmm ; movlps xmm,m64 */
        unsigned char *stub = arena + used;
        unsigned int reg = (unsigned int)((p[3] >> 3) & 7);
        long long rel;
        size_t need = 3 + 2 + (size_t)oplen + 1;
        if (used + need > arena_len) { ++remaining; break; }
        stub[0] = 0x0f; stub[1] = 0x57;
        stub[2] = (unsigned char)(0xc0 | (reg << 3) | reg);
        stub[3] = 0x0f; stub[4] = 0x12;
        memcpy(stub + 5, p + 3, (size_t)oplen);
        stub[5 + oplen] = 0xc3;
        rel = (long long)(stub - (p + 5));
        if (rel < -2147483647LL || rel > 2147483647LL) { ++remaining; break; }
        p[0] = 0xe8;
        p[1] = (unsigned char)(rel & 0xff);
        p[2] = (unsigned char)((rel >> 8) & 0xff);
        p[3] = (unsigned char)((rel >> 16) & 0xff);
        p[4] = (unsigned char)((rel >> 24) & 0xff);
        memset(p + 5, 0x90, (size_t)len - 5);
        used += need;
        ++hits;
        break;
      }
      case 6: {                          /* the x87 takes the square root */
        unsigned char *stub = arena + used;
        unsigned int reg = (unsigned int)((p[3] >> 3) & 7);
        size_t n = 0;
        long long rel;
        if (used + 32 + (size_t)oplen > arena_len) { ++remaining; break; }
        stub[n++] = 0x8d; stub[n++] = 0x64;                    /* lea esp,-8 */
        stub[n++] = 0x24; stub[n++] = 0xf8;
        stub[n++] = 0xdd;                                       /* fld qword */
        /* DD /0: the reg field selects the opcode extension, not a register */
        stub[n++] = (unsigned char)(p[3] & 0xc7);
        memcpy(stub + n, p + 4, (size_t)oplen - 1); n += (size_t)oplen - 1;
        stub[n++] = 0xd9; stub[n++] = 0xfa;                     /* fsqrt     */
        stub[n++] = 0xdd; stub[n++] = 0x1c; stub[n++] = 0x24;   /* fstp [esp]*/
        stub[n++] = 0x0f; stub[n++] = 0x12;                     /* movlps    */
        stub[n++] = (unsigned char)(0x04 | (reg << 3));         /*  xmm,[esp]*/
        stub[n++] = 0x24;
        stub[n++] = 0x8d; stub[n++] = 0x64;                     /* lea esp,+8 */
        stub[n++] = 0x24; stub[n++] = 0x08;
        stub[n++] = 0xc3;
        rel = (long long)(stub - (p + 5));
        if (rel < -2147483647LL || rel > 2147483647LL) { ++remaining; break; }
        p[0] = 0xe8;
        p[1] = (unsigned char)(rel & 0xff);
        p[2] = (unsigned char)((rel >> 8) & 0xff);
        p[3] = (unsigned char)((rel >> 16) & 0xff);
        p[4] = (unsigned char)((rel >> 24) & 0xff);
        memset(p + 5, 0x90, (size_t)len - 5);
        used += n;
        ++hits;
        break;
      }
      default:                           /* handled by the conversion pass */
        break;
    }
  }
  {
    int c = scva_sse2_patch_cvt(base, arena, arena_len, &used);
    if (c < 0) return -1;
    hits += c;
    remaining += SCVA_SSE2_CVTS - c;
  }
  if (left) *left = remaining;
  return hits;
}

#if defined(_WIN32) && defined(SCVA_SHIM_HOST_APPLY)
/* The Windows hosts hand the core to LoadLibrary, so the code arrives already
   protected and relocated; the patch opens it and takes its stub arena from
   VirtualAlloc. windows.h is included by the host before this header. */
static int scva_sse2_apply(void *module)
{
  unsigned char *base = (unsigned char *)module;
  unsigned char *nt, *sec, *arena;
  unsigned short nsec, optsz;
  DWORD old;
  int i, left = 0, done;
  const char *force = getenv("SCVA_SSE2");

  if (force ? (*force == '0') : scva_cpu_has_sse2()) return 0;
  if (!base || base[0] != 'M' || base[1] != 'Z') return 0;
  nt = base + *(const int *)(base + 0x3c);
  if (nt[0] != 'P' || nt[1] != 'E') return 0;
  nsec  = *(const unsigned short *)(nt + 6);
  optsz = *(const unsigned short *)(nt + 20);
  sec   = nt + 24 + optsz;

  arena = (unsigned char *)VirtualAlloc(NULL, SCVA_SSE2_ARENA,
            MEM_COMMIT | MEM_RESERVE, PAGE_EXECUTE_READWRITE);
  if (!arena) return 0;

  for (i = 0; i < (int)nsec; ++i) {         /* the code has to be writable */
    const unsigned char *e = sec + i * 40;
    unsigned int vsize = *(const unsigned int *)(e + 8);
    unsigned int vaddr = *(const unsigned int *)(e + 12);
    unsigned int chars = *(const unsigned int *)(e + 36);
    if ((chars & 0x20000000) && vsize)
      VirtualProtect(base + vaddr, vsize, PAGE_EXECUTE_READWRITE, &old);
  }
  done = scva_sse2_patch(base, arena, SCVA_SSE2_ARENA, &left);
  return done < 0 ? -1 : done;
}
#endif
#endif
